### ISSUE TITLE
There is a similar help to learn Japanese software, I hope to help the author.

### ISSUE THREAD

**Issue by ads233** [LostArrows27/anime-subtitle-player#1]
Search hockyy/miteiru on github this project has a function to annotate the English source of Japanese kanji + Japanese loanwords, hoping to help the author's software development![292813609-45e92433-bf7a-43e8-9370-6560b46ac431.png](https://github.com/LostArrows27/anime-subtitle-player/assets/153071412/c16e35f3-b8b3-4510-8227-7351e61d352b)

**Comment by LostArrows27** [comment]
@ads233 thanks man, appericiate for the recommend. I have developed the hover translation too which pretty similar to this but still in process and pretty buggy tho if u have tried :D 
P/S: From the beginning, i code this like a tool for me so that i can directly hover and get translation with Yomichan in the subtitle of the video. I never thought that there will actually people out there know that my website exist one day lol. You really made my day man 👊

**Comment by ads233** [comment]
Has the author ever used miteiru?
I would like to ask how to implement miteiru's Mecab and Custom Dictionary Setup and MeCab Dictionary Customization in Windows system? After I changed the dictionary path, the function of English annotation and Japanese kanji Furigana annotation was invalid.
I asked the author of miteiru if he could give me a graphic or video tutorial, but he replied (Im very busy atm, windows mecab setting is availablr online I think, you can look it up on google.) Then I used a browser search, but still can't understand (no graphic tutorial I am hard to understand)😭😭😭
![1](https://github.com/LostArrows27/anime-subtitle-player/assets/153071412/90f2b72d-8962-458a-ada8-6a470bafe13d)
![2](https://github.com/LostArrows27/anime-subtitle-player/assets/153071412/423044fc-cbeb-4414-8041-7a6f705cb6c1)
![3](https://github.com/LostArrows27/anime-subtitle-player/assets/153071412/78d9fd72-ab14-49ba-9f43-02e3ec1e3f76)
![4](https://github.com/LostArrows27/anime-subtitle-player/assets/153071412/d4b5dbed-905d-4e70-827c-1bbe5a2a3cc2)

**Comment by LostArrows27** [comment]
@ads233 till now i just use Yomichan in browser for immersion so havent tried Miteiru yet.... But according to your picture, i saw that u already success in installing Mecab right ? But i guess u can clear the cache and check if is there any error first of the dictionary. 
![image](https://github.com/LostArrows27/anime-subtitle-player/assets/97510841/baaca85c-93c7-4064-9cb1-ccfe8843b6a8)

**Comment by ads233** [comment]
I've cleared the cache, but it's still like this!!

**Comment by ads233** [comment]
I have found a software in the Chinese area that can play the role of real-time translation, and use it to combine miteiru to display the translation of native language subtitles through shortcut keys when native language subtitles are needed to help understand the meaning of Japanese subtitles. In addition, I asked my friend to modify miteiru to copy the entire subtitle to the clip version every time, and through KDE Connect, I will automatically send the copied content on the computer to the mobile phone for analysis at any time, so that I can use my native language (Chinese to quickly analyze on the mobile phone).On the computer side, you can also use the LunaTranslator to call your native language and translate the whole subtitle at any time through shortcut keys when you need to see the translation of native language subtitles:

**Comment by ads233** [comment]
![222](https://github.com/LostArrows27/anime-subtitle-player/assets/153071412/ebb99ce5-98e8-4dc8-8e22-b4c848d836d3)

**Comment by ads233** [comment]
https://github.com/HIllya51/LunaTranslator

**Comment by LostArrows27** [comment]
@ads233  nice to hear that bro, but it seem a bit much information on the screen right. You can also consider this way to  immersion by Matt VS Japan https://www.youtube.com/watch?v=bbg6ztWecbU&t=408s. But anyway good luck on your Japanese journey man, just tell me anything if i can help you 😇

**Comment by ads233** [comment]
https://youtu.be/rilQoQht7PY
In fact, the effect I want is this (Furigana+Meaning), and secondly, because my English is not good, I sometimes need to use LunaTranslator to translate in Chinese. I hope your app can also add Furigana+English Meaning, and then automatically copy the real-time subtitles to the clip version of the computer, so that I can push the information to the LunaTranslator in real time. Or KDE Connect can sync the copied live subtitles to my phone for analysis.

**Comment by ads233** [comment]
Because I haven't seen any other free software that can achieve this effect, I choose miteiru. But miteiru's built-in dictionary isn't good enough, That's why I was wondering if you could help me set up his instructions (Mecab and Custom Dictionary Setup (Optional)) and (MeCab Dictionary Customization). I would be grateful if you could provide me with a video or graphic setup tutorial...

**Comment by ads233** [comment]
In addition, I combined with other Notebooks to make a model that only requires web video connection to make subtitles with whisper V3 model, and the accuracy of the subtitles produced is good. Try it if you need it.
https://colab.research.google.com/drive/1FrKV1TFra5joJ8tRI8zwTTuMQGj5WugH

**Comment by ads233** [comment]
Due to the influence of my mother tongue, I cannot accurately infer the correct pronunciation of some Japanese kanji simply by listening. In addition, Japanese loanwords from English, if I do not have English sources to assist understanding, as a Chinese native speaker, I have a hard time remembering these types of words. So I've been looking for video players with both of these features...

**Comment by LostArrows27** [comment]
@ads233 

> In addition, I combined with other Notebooks to make a model that only requires web video connection to make subtitles with whisper V3 model, and the accuracy of the subtitles produced is good. Try it if you need it. https://colab.research.google.com/drive/1FrKV1TFra5joJ8tRI8zwTTuMQGj5WugH

yo nice bro, i had try whisper V3 model too but just planning to apply it in syncing subtitle with video, will consider try urs model in the feature man:D

**Comment by ads233** [comment]
![QQ截图20240129132345](https://github.com/LostArrows27/anime-subtitle-player/assets/153071412/e3f27227-268d-4d97-8b47-51224da2107d)

**Comment by LostArrows27** [comment]
> Due to the influence of my mother tongue, I cannot accurately infer the correct pronunciation of some Japanese kanji simply by listening. In addition, Japanese loanwords from English, if I do not have English sources to assist understanding, as a Chinese native speaker, I have a hard time remembering these types of words. So I've been looking for video players with both of these features｛Hover｝： (Furigana+English Meaning)...

have you try search for some Yomichan Dictionary in your language, i have found some JMDict in both Vietnamese and English and it helps me a lot

**Comment by ads233** [comment]
I am trying, in fact, I prefer to obtain the video subtitles in the player to the mobile phone for analysis at any time, and the computer side relies on {Hover} : (Furigana+English Meaning) to watch the video intently

**Comment by LostArrows27** [comment]
@ads233 yeah sorry can help you much cause i recently just stick with my browser in immersion Japanese 😢

**Comment by ads233** [comment]
It's OK, please refuel to develop your software. If your software can add the functions I mentioned, it will be more useful. In addition, I am used to conducting in-depth analysis of Japanese in my mobile phone, as follows(KDE Connect for PCs and phones):
https://youtube.com/shorts/Ut7E43iUQIM?feature=share

**Comment by LostArrows27** [comment]
@ads233 okay man, a bit busy atm but when available i will continue develop this repo. Thanks again for the feedback man, please waiting for some new feature in the future 🤝

**Comment by LostArrows27** [comment]
@ads233 i just found and use an app called Jidoujisho for a while, pretty good app for immersion with Anime, any video source, novel, manga, .... 
The app reposity is here with pretty detail instruction: https://github.com/lrorpilla/jidoujisho
P/S: If you want instruction in video you can also watch this video from Jarods :D https://www.youtube.com/watch?v=vxuodjzNBXw

**Comment by ads233** [comment]
Thanks for sharing.  By the way, the author of miteiru told me that I could use the following project to get the translation. Since I do not understand programming, I do not know whether it refers to Hover translate. I hope it will be helpful to your software development.
https://github.com/sinedie/SRTranslator/tree/master
![截图_20240206130858](https://github.com/LostArrows27/anime-subtitle-player/assets/153071412/e299b153-6af2-4d96-b182-912d999a8e11)

**Comment by ads233** [comment]
I have some good news: If your software adds a feature that automatically copies subtitles to computer's clipboard, when combined with this software， That's perfect！

**Comment by ads233** [comment]
github.com/ks233/ja-learner
